language: python
python:
- '3.6'
install: pip install tox-travis
script: tox
notifications:
  webhooks:
    urls:
      secure: S3Mv3IkC7wYcWJT+OrIVliE2TA25xvM3iprqZTr8mP1x6W88k40m7ZVwmvFLd6EbyXj3SUoJncLWGgqJDohbnNC1p1Mte5mn4ZgiKXiEkIZwg1m8hpct1pXdnIsGxXnW4VKfOEKO5BkcvqkqhXvMe7/jCqCA/jiwQFQGY9wpbZJXTmcvbPOSchKecJ8CHTjDXTbRKfPLj7cb3hIBcbkytVUVf7S0hBxZ4VEruhrTKW8IWfQW+Aty+8mOkjHcsLo4KvxwqrTeuPiAmjXXXxYPT3UfQVn7JEFsiq7o8MU0akwoHxMMh3jPhbZCA/l77SCkneuO0fjGU0Xw8XbLQxwknfg/zAUOryIGA2T+xLxfEW8IScc0YvZF0hnC7fF3PrO5izzZOwwgMJLVBaFJyULDac8UMNmRCLiZwUjaDXT8zA1VomxMex8tCsa0QGT99ohu4AT+tHLJ4oq8e/BUZp4ikuN9ORMeAhi1ZpGNwIjSuHfNCwe8ltIYhjxP7WXifW6euf+G44xi3fO4EPsSqF8WYLF58V/c+RyuVNr34xyYDPILhlnxVOb3mXkfw7de5IKtjR8dAfWeqdQGxoNg6Jhm23nTsQ9DTXq/2zVn5XaQIXeRbSuQy5CAvixp922QKS0NZ4F3nwPM0uze36EuMhkbeR0L4p2Vo+gtYbMEajWk9L4=
    on_success: always
    on_failure: never
    on_start: never
    on_cancel: never
    on_error: never
