language: python
python:
- '3.6'
install: pip install tox-travis
script: tox
notifications:
  webhooks:
    on_success: always
    on_failure: never
    on_start: never
    on_cancel: never
    on_error: never
    if: branch = master
    urls:
      secure: HtqXZzQgmxVr6y2cp4fgfP1vmXvZDRl5seDWU+LuqJkSCBjuH9qa6LESslNnzvHJsw5lDBTfd49KhPOInUJXoZkKncnvU1rI3PM4ywC1BgAfpiNQ0uzjjP6DlwYpmCErN90Zg5Vm2Nif6/RfagYCkAfxwl4Rkwcmyk12gwR3JEwrL91PduhE23r+oJD3liuJuc1gSNvMmGPIaxQabHMfGgdUkmOE/kKZ8b/nPWQrJMNYr/2C5gAjeVT3Ah8DJzBah7OWOFmNgG20RNzOCZ3l+dLB63jP1WY+wY+JXk3ghl3zVYTxm6Ni94Zc3QjpFKIcxMDGen9SIjRdXcPRsiRr9+R4JPyUJRLS3srirdWKVm7PxPHemzT9a5y9e9b/Whh2PTIMPpqwnjF/TVSF+Z9zUjFQYpEgC/rFfILpSTIPRBfX6qKYZv4DzjteJcQxKdt7A4xpATFXVBkhN9AluiM1Pd8CMSTwVpkcN9Yjw6bogY3rMUsn4vUXVkcPsfoJgIdR6HoPk5sFxDfggeBENFP0/hmzpV/GXqMqtHjZlJlMpBwlW2QRf1h3n1nO1bpDKdxpNB+evbW5gw5qvTgBquMs74X6dho6FguI3Lh74Ka7HDLbDaRflgkDhiCSryGcKzAlgThVusOG/av6HE+0P+my26UgFt2zhF6NBSJmFAjqOF4=
